In [9]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

years = range(2011, 2017)
files = ['CRNS0101-05-%d-CA_Yosemite_Village_12_W.txt' % y for y in years]
usecols = [1, 2, 8]

data = [np.loadtxt(f, usecols=usecols) for f in files]
data = np.vstack(data)

data[:10]

# Map from HHmm to an integer
data[:, 1] = np.floor_divide(data[:, 1], 100) * 60 + np.mod(data[:, 1], 100)
valid = data[:, 2] > -1000

x_train = data[valid, 1].reshape(-1, 1)
y_train = data[valid, 2]
regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)

x_predict = [[0], [1435]]
y_predict = regr.predict(x_predict)


In [ ]:
#plot
plt.scatter(data[valid, 1], data[valid, 2], label='Data', color='b')
plt.plot(x_predict, y_predict, label='Linear prediction', color='r')
plt.legend(loc='best')
plt.show()

In [4]:
data[:1]

array([[  2.01101010e+07,   5.00000000e+00,  -6.40000000e+00]])

In [6]:
x_train[:1]

array([[ 5.]])

In [8]:
y_train[:1]

array([-6.4])

In [ ]:
# FIT RBF LINEAR MODEL

from sklearn.metrics.pairwise import rbf_kernel
import numpy as np

centers = np.asarray([1.0, 1.2, 1.4, 1.6, 1.8, 2.0])
sigma = 1.0
# New representation:
x_rbfd = rbf_kernel(x_train, centers, gamma=1/sigma^2)

# Now go and fit a linear model between x and height
regr.fit(x_rbfd + x_rbfd**2 + x_rbfd**3, y_train)
